<?php

return [
    'plan-digital-gamou' => [
        'name' => 'Plan digital Gamou',
        'status' => 'TERMINÉ',
        'start' => '01 sept 2025',
        'end' => '30 nov 2025',
        'progress' => 100,
        'cover_image' => '/media/Gamou/Onas-Meteo Template.webp',
        'cover_image_mobile' => '/media/Gamou/Onas-Meteo.webp',
        'objective' => 'Conception du dispositif digital Gamou : objectifs, messages clés et feuille de route de production pour encadrer les livrables ONAS.',
        'timeline_intro' => [
            'Le plan digital Gamou est né d’un diagnostic terrain mené avec les équipes ONAS pendant l’hivernage. Nous avons identifié les attentes des pèlerins, les problématiques d’assainissement et les moments de vérité à couvrir.',
            'Cette page retrace les jalons du dispositif, des objectifs jusqu’à la mise en production des contenus. Chaque étape renvoie vers les livrables associés et les productions créatives ou vidéo qui en découlent.',
        ],
        'contact' => [
            'name' => 'Elhadji NDIAYE',
            'role' => 'CEO Levell',
            'phone' => '+221 776789212',
            'email' => 'elhadji.ndiaye@levellagency.com',
            'avatar' => '/media/photo_elj.jpg',
            'avatar_position' => 'top',
        ],
        'timeline' => [
            [
                'title' => 'Diagnostic & objectifs',
                'description' => 'Atelier ONAS x Levell pour cadrer les enjeux, cartographier les audiences clés et formaliser les objectifs de communication.',
                'date' => 'sept 2025',
                'status' => 'completed',
                'icon' => 'analysis',
                'anchor' => 'kickoff-plan-digital-gamou',
                'narrative_before' => 'Nous avons commencé par écouter les équipes ONAS (siège, délégation, terrain) afin de comprendre les attentes des pèlerins et des riverains. Ce diagnostic dégage les priorités de communication : information service, prévention et valorisation des actions terrain.',
            ],
            [
                'title' => 'Plan digital Gamou 2025',
                'description' => 'Objectifs, axes éditoriaux et rétroplanning de production consolidés dans un document unique partagé avec l’ONAS.',
                'date' => 'oct 2025',
                'status' => 'completed',
                'icon' => 'plan',
                'anchor' => 'plan-digital-gamou-2025',
                'assets' => [
                    [
                        'type' => 'pdf',
                        'label' => 'Plan digital Gamou 2025',
                        'href' => '/media/Gamou/ONAS - Plan Digital Gamou 2025.pdf',
                        'status' => 'prêt',
                    ],
                    [
                        'type' => 'link',
                        'label' => 'Voir les créas issues du plan',
                        'href' => '/onas/projets/creas-gamou',
                        'status' => 'en ligne',
                    ],
                ],
                'narrative_before' => 'Le livrable synthétise les messages clés par audience, les temps forts à couvrir et la tonalité à adopter. Il sert de boussole pour les équipes créatives et vidéo.',
            ],
            [
                'title' => 'Cadre de production',
                'description' => 'Construction du rétroplanning de conception (formats, contenus, validations) et mise en place des rituels de suivi avec les équipes ONAS.',
                'date' => 'oct 2025',
                'status' => 'completed',
                'icon' => 'roadmap',
                'anchor' => 'calendrier-activation-gamou',
                'narrative_before' => 'Chaque temps fort (annonce, sensibilisation, bilan) est décliné en formats à produire, responsables et jalons de validation. Nous priorisons les supports utiles aux équipes terrain et aux créatifs chargés de la production.',
                'assets' => [
                    [
                        'type' => 'link',
                        'label' => 'Découvrir la campagne vidéo',
                        'href' => '/onas/projets/gamou',
                        'status' => 'en ligne',
                    ],
                ],
            ],
            [
                'title' => 'Passage de relais créa & vidéo',
                'description' => 'Brief croisé des équipes créatives et vidéo pour produire les contenus Gamou (social, print, captation).',
                'date' => 'nov 2025',
                'status' => 'completed',
                'icon' => 'creative',
                'anchor' => 'brief-crea-video-gamou',
                'assets' => [
                    [
                        'type' => 'link',
                        'label' => 'Accéder aux créations Gamou',
                        'href' => '/onas/projets/creas-gamou',
                        'status' => 'à consulter',
                    ],
                    [
                        'type' => 'link',
                        'label' => 'Voir la vidéo Gamou',
                        'href' => '/onas/projets/gamou',
                        'status' => 'à visionner',
                    ],
                ],
                'narrative_before' => 'Une fois le plan validé, nous travaillons main dans la main avec les équipes créatives et vidéo pour assurer la cohérence des livrables finaux.',
            ],
        ],
    ],

    'creas-gamou' => [
        'name' => 'Créas Gamou',
        'status' => 'TERMINÉ',
        'start' => '15 oct 2025',
        'end' => '30 nov 2025',
        'progress' => 100,
        'cover_image' => '/media/Gamou/Onas-Gamou.webp',
        'cover_image_mobile' => '/media/Gamou/Onas-Gamou.png',
        'objective' => 'Centraliser les créations print & social issues du plan digital Gamou : moodboard, déclinaisons et fichiers sources prêts à diffuser.',
        'contact' => [
            'name' => 'Ousmane Manel FALL',
            'role' => 'Directeur Artistique',
            'phone' => '773478428',
            'email' => 'ousmane.fall@levellagency.com',
            'avatar' => '/media/photo_ousmane.jpg',
            'avatar_position' => 'top',
        ],
        'timeline_intro' => [
            'Le plan digital a rapidement laissé place à une phase de création intense. Les visuels ci-dessous matérialisent la narration imaginée pour l’ONAS autour du Gamou.',
            'Chaque étape réunit les assets validés ainsi que des liens directs vers le plan stratégique et la captation vidéo pour garder une vision 360° du dispositif.',
        ],
        'timeline' => [
            [
                'title' => 'Moodboard & intentions graphiques',
                'description' => 'Sélection d’univers visuels, tonalité iconographique et axes narratifs pour illustrer l’engagement ONAS pendant le Gamou.',
                'date' => 'oct 2025',
                'status' => 'completed',
                'icon' => 'creative',
                'anchor' => 'moodboard-gamou',
                'images' => [
                    '/media/Gamou/ONAS - Conseil Couvercle.webp',
                    '/media/Gamou/Onas-Latence.webp',
                    '/media/Gamou/Onas-Meteo Template.webp',
                ],
                'images_display' => 'modal',
                'images_button_label' => 'Voir le moodboard',
                'narrative_before' => 'Nous avons travaillé un univers modernisé qui reste institutionnel tout en donnant de la place aux gestes utiles et à l’action de l’ONAS sur le terrain.',
                'assets' => [
                    [
                        'type' => 'link',
                        'label' => 'Consulter le plan digital',
                        'href' => '/onas/projets/plan-digital-gamou',
                        'status' => 'en ligne',
                    ],
                ],
            ],
            [
                'title' => 'Kit social media',
                'description' => 'Déclinaisons pour les formats story, feed, reels et publications informative destinées aux différents temps du Gamou.',
                'date' => 'oct 2025',
                'status' => 'completed',
                'icon' => 'social',
                'anchor' => 'kit-social-gamou',
                'images' => [
                    '/media/Gamou/Onas-Poubelle.webp',
                    '/media/Gamou/Onas-fosse septique.webp',
                    '/media/Gamou/Onas-Meteo.webp',
                    '/media/Gamou/Onas-Sensibilisation Mobile.webp',
                    '/media/Gamou/Onas-plaque vole.webp',
                ],
                'images_display' => 'modal',
                'images_button_label' => 'Afficher le kit social media',
                'narrative_before' => 'Chaque visuel décline un message de prévention ou d’information pratique : numéros d’urgence, consignes d’assainissement, météo, valorisation des équipes terrain.',
            ],
            [
                'title' => 'Fichiers sources & exports',
                'description' => 'Mise à disposition des PSD et exports haute définition pour faciliter les adaptations locales.',
                'date' => 'oct 2025',
                'status' => 'completed',
                'icon' => 'goodies',
                'anchor' => 'fichiers-sources-gamou',
                'assets' => [
                    [
                        'type' => 'source',
                        'label' => 'Pack PSD Gamou',
                        'href' => '/media/Gamou/Sources/ONAS - NumerosUrgence.psd',
                        'status' => 'téléchargeable',
                    ],
                    [
                        'type' => 'source',
                        'label' => 'Sensibilisation mobile',
                        'href' => '/media/Gamou/Sources/Onas-Sensibilisation Mobile.psd',
                        'status' => 'téléchargeable',
                    ],
                    [
                        'type' => 'source',
                        'label' => 'Météo',
                        'href' => '/media/Gamou/Sources/Onas-Meteo.psd',
                        'status' => 'téléchargeable',
                    ],
                ],
                'narrative_before' => 'Les fichiers sources permettent aux équipes régionales ONAS de personnaliser les messages tout en restant alignées sur la charte.',
            ],
            [
                'title' => 'Coordination vidéo officielle',
                'description' => 'Passage de relais à l’équipe vidéo pour capter le Gamou et aligner le montage sur la direction artistique définie.',
                'date' => 'nov 2025',
                'status' => 'completed',
                'icon' => 'video',
                'anchor' => 'coordination-video-gamou',
                'assets' => [
                    [
                        'type' => 'link',
                        'label' => 'Voir la campagne vidéo',
                        'href' => '/onas/projets/gamou',
                        'status' => 'à visionner',
                    ],
                    [
                        'type' => 'link',
                        'label' => 'Retour au plan digital',
                        'href' => '/onas/projets/plan-digital-gamou',
                        'status' => 'en ligne',
                    ],
                ],
                'narrative_before' => 'Les créations servent de guide à la captation : cadrages, messages forts, identité graphique. La vidéo s’inscrit dans cette même ligne narrative pour valoriser l’action de l’ONAS sur place.',
            ],
        ],
    ],

    'gamou' => [
        'name' => 'Video Gamou',
        'status' => 'TERMINÉ',
        'start' => '05 sept 2025',
        'end' => '18 oct 2025',
        'progress' => 100,
        'cover_image' => '/media/onas-gamou.jpg',
        'objective' => 'Couverture 360° du Gamou : production de contenus (photo, vidéo), social media, diffusion publique pour renforcer la visibilité de l’ONAS auprès des pèlerins.',
        'timeline_intro' => [
            'Le projet de réalisation de deux capsules vidéo sur le Grand Gamou à Tivaouane et Kaolack s’est déroulé dans un contexte exigeant, marqué par une forte affluence et une mobilisation importante des équipes sur le terrain. Nous avons choisi d’adopter une approche proactive, en avançant simultanément sur toutes les étapes de production afin de garantir un rendu final de qualité et dans les délais impartis.',
        ],
        'contact' => [
            'name' => 'Paul Bernard Ndiaye',
            'role' => 'Video Producer',
            'phone' => '781560794',
            'email' => 'paul.ndiaye@levellagency.com',
            'avatar' => '/media/photo_paul_square.jpg',
        ],
        'timeline' => [
            [
                'title' => 'Tournage (Kaolack - Tivaouane)',
                'description' => 'Captation des événements du Gamou à Kaolack et Tivaone.',
                'date' => 'fin sept 2025',
                'status' => 'completed',
                'icon' => 'shoot',
                'narrative_before' => 'La phase de tournage a ensuite été réalisée sur place, à Tivaouane et Kaolack, où les équipes de l’ONAS étaient déployées comme des camions de vidange et des mini-stations de pompage pour gérer l’importante affluence. L’objectif était de capturer des images authentiques et représentatives de l’ampleur du dispositif, tout en respectant la fluidité des opérations et la sécurité sur le terrain.',
            ],
            [
                'title' => 'Montage',
                'description' => 'Assemblage image/son et animations explicatives.',
                'date' => 'début oct 2025',
                'status' => 'completed',
                'icon' => 'montage',
                'narrative_before' => 'Lors du montage, les séquences ont été assemblées avec des éléments graphiques et des animations légères pour renforcer la compréhension et l’impact visuel du dispositif.',
            ],
            [
                'title' => 'Video Finale',
                'description' => 'Montage et post-production des capsules finales (Tivaouane & Kaolack).',
                'date' => 'début oct 2025',
                'status' => 'completed',
                'icon' => 'video',
                'videos' => [
                    ['src' => '/media/Sama Naweet/TIV VERS 2 720P 3.mp4', 'orientation' => 'portrait'],
                    ['src' => '/media/Sama Naweet/Video CAMIONS HD.mp4', 'orientation' => 'portrait'],
                ],
                'narrative_before' => 'Enfin, les deux versions finales ont été produites en intégrant les retours des équipes de l’ONAS, reflétant fidèlement le rôle stratégique et opérationnel de l’Office lors de cet événement majeur, tout en offrant des capsules claires, engageantes et représentatives de l’ampleur du Grand Gamou.',
            ],
        ],
    ],

    'spot-sama-naweet' => [
        'name' => 'Spot Sama Naweet',
        'status' => 'TERMINÉ',
        'start' => '01 sept 2025',
        'end' => '12 oct 2025',
        'progress' => 100,
        'cover_image' => '/media/onas-spot.jpg',
        'objective' => 'Spot vidéo de sensibilisation ONAS pour éduquer les usagers aux bons comportements d’assainissement et aux comportements responsables.',
        'timeline_intro' => [
            'Le spot publicitaire de l’ONAS a été réalisé dans un contexte hivernal exigeant, avec des équipes fortement mobilisées sur le terrain. Pour avancer efficacement, nous avons adopté une démarche proactive, tout en revisitant le scénario proposé par l’ONAS afin d’en renforcer la cohérence et l’impact visuel.',
        ],
        'contact' => [
            'name' => 'Paul Bernard Ndiaye',
            'role' => 'Video Producer',
            'phone' => '781560794',
            'email' => 'paul.ndiaye@levellagency.com',
            'avatar' => '/media/photo_paul_square.jpg',
        ],
        'timeline' => [
            [
                'title' => 'Scénario',
                'description' => 'Écriture du concept et du message clé ONAS.',
                'date' => 'début sept 2025',
                'status' => 'completed',
                'icon' => 'plan',
                'pdf' => '/media/Sama Naweet/Copie de Spot ONAS_Définitif Client.pdf',
                'assets' => [
                    [
                        'type' => 'pdf',
                        'label' => 'Scénario final (PDF)',
                        'href' => '/media/Sama Naweet/Copie de Spot ONAS_Définitif Client.pdf',
                        'status' => 'prêt',
                    ],
                ],
                'narrative_before' => 'Nous avons d’abord travaillé sur le scénario, en définissant un fil conducteur clair et cohérent, capable de valoriser les missions et les réalisations de l’ONAS tout en restant accessible au grand public. Cette étape a permis d’établir le ton, le rythme et les messages clés de la vidéo.',
            ],
            [
                'title' => 'Tournage',
                'description' => 'Captation terrain avec les équipes ONAS et scènes d’usage réel.',
                'date' => 'mi sept 2025',
                'status' => 'completed',
                'icon' => 'shoot',
                'images_display' => 'modal',
                'images_button_label' => 'Voir les backstages',
                'images' => [
                    '/media/Sama Naweet/Backstages/DSC05939.JPG',
                    '/media/Sama Naweet/Backstages/DSC05946.JPG',
                    '/media/Sama Naweet/Backstages/DSC05949.JPG',
                    '/media/Sama Naweet/Backstages/DSC05950.JPG',
                    '/media/Sama Naweet/Backstages/DSC05954.JPG',
                    '/media/Sama Naweet/Backstages/DSC05955.JPG',
                    '/media/Sama Naweet/Backstages/DSC05959.JPG',
                    '/media/Sama Naweet/Backstages/DSC05967.JPG',
                    '/media/Sama Naweet/Backstages/DSC05983.JPG',
                    '/media/Sama Naweet/Backstages/DSC06023.JPG',
                    '/media/Sama Naweet/Backstages/DSC06048.JPG',
                ],
                'narrative_before' => 'Nous sommes ensuite passés à la phase de tournage, réalisée sur plusieurs sites représentatifs des activités de l’ONAS. L’objectif était de capturer des images authentiques, dynamiques et illustratives du travail mené sur le terrain, en veillant à la qualité des prises de vue et à la cohérence visuelle avec l’identité de l’institution.',
            ],
            [
                'title' => 'Montage',
                'description' => 'Montage image/son, voix off, sous-titrage.',
                'date' => 'fin sept 2025',
                'status' => 'completed',
                'icon' => 'montage',
                'narrative_before' => 'À partir de ce matériau, nous avons entamé la phase de montage, en combinant les séquences tournées avec des éléments graphiques, des animations et une bande sonore adaptée. Cette étape a permis de renforcer la narration et d’assurer une mise en valeur harmonieuse des contenus.',
            ],
            [
                'title' => 'Version finale',
                'description' => 'Intégration de l’identité ONAS et habillage graphique.',
                'date' => 'début oct 2025',
                'status' => 'completed',
                'icon' => 'video',
                'youtube_id' => 'OoWkhQLAmp4',
                'narrative_before' => 'Enfin, une version finale a été produite, intégrant les ajustements issus des retours de l’équipe de l’ONAS. Cette version reflète fidèlement la vision du projet : une vidéo institutionnelle moderne, engageante et alignée avec la nouvelle image de l’Office.',
            ],
            [
                'title' => 'Fichiers dispos',
                'description' => 'Export en plusieurs formats prêts diffusion.',
                'date' => '12 oct 2025',
                'status' => 'completed',
                'icon' => 'delivery',
                'narrative_before' => 'Après validation, nous avons décliné le spot dans tous les formats attendus pour faciliter sa diffusion immédiate sur les canaux ONAS et les médias partenaires.',
            ],
        ],
    ],

    'creas-tabaski' => [
        'name' => 'Créas Tabaski',
        'status' => 'TERMINÉ',
        'start' => '01 août 2025',
        'end' => '30 sept 2025',
        'progress' => 100,
        'cover_image' => '/media/Crea Tabaski/Créa Tabaski Officiel Mockup 2.png',
        'cover_image_mobile' => '/media/Crea Tabaski/Créa Tabaski Officiel Mockup.png',
        'objective' => 'Concevoir la campagne de sensibilisation Tabaski : positionnement créatif, maquettes officielles, déclinaisons print et fichiers sources prêts à l’emploi.',
        'contact' => [
            'name' => 'Ousmane Manel FALL',
            'role' => 'Directeur Artistique',
            'phone' => '773478428',
            'email' => 'ousmane.fall@levellagency.com',
            'avatar' => '/media/photo_ousmane.jpg',
            'avatar_position' => 'top',
        ],
        'timeline_intro' => [
            'Le brief Tabaski s’appuie sur l’héritage du plan digital Gamou tout en adressant les enjeux spécifiques de la fête (nettoiement des caniveaux, gestes responsables).',
            'Chaque étape ci-dessous met à disposition les éléments validés ainsi qu’un accès direct aux ressources pour adaptation locale.',
        ],
        'timeline' => [
            [
                'title' => 'Brief & messages clés',
                'description' => 'Synthèse des enjeux Tabaski, audiences prioritaires et axes de communication ONAS.',
                'date' => 'août 2025',
                'status' => 'completed',
                'icon' => 'analysis',
                'anchor' => 'brief-tabaski',
                'assets' => [
                    [
                        'type' => 'doc',
                        'label' => 'Brief créa Tabaski (.xmind)',
                        'href' => '/media/Crea Tabaski/Brief Créa ONAS.xmind',
                        'status' => 'téléchargeable',
                    ],
                ],
            ],
            [
                'title' => 'Maquette officielle',
                'description' => 'Visuels clés validés pour diffusion : identité Tabaski et déclinaisons social media.',
                'date' => 'sept 2025',
                'status' => 'completed',
                'icon' => 'creative',
                'anchor' => 'maquettes-social-tabaski',
                'images' => [
                    '/media/Crea Tabaski/Créa Tabaski Officiel Mockup.png',
                    '/media/Crea Tabaski/Créa Tabaski - Modif M. Lam.png',
                    '/media/Crea Tabaski/Créa Tabaski.png',
                ],
                'images_display' => 'modal',
                'images_button_label' => 'Afficher les maquettes Tabaski',
                'assets' => [
                    [
                        'type' => 'pdf',
                        'label' => 'Créa Tabaski officielle (PDF)',
                        'href' => '/media/Crea Tabaski/Créa Tabaski Officiel.pdf',
                        'status' => 'prêt',
                    ],
                ],
            ],
            [
                'title' => 'Déclinaisons print & terrain',
                'description' => 'Variantes bus et affichage terrain pour maximiser la visibilité pendant la fête.',
                'date' => 'sept 2025',
                'status' => 'completed',
                'icon' => 'goodies',
                'anchor' => 'declinaisons-print-tabaski',
                'images' => [
                    '/media/Crea Tabaski/Créa Tabaski Officiel Mockup 2.png',
                    '/media/Crea Tabaski/Créa Tabaski Bus.png',
                ],
                'images_display' => 'modal',
                'images_button_label' => 'Voir les déclinaisons print',
                'assets' => [
                    [
                        'type' => 'pdf',
                        'label' => 'Créa Tabaski Bus (PDF)',
                        'href' => '/media/Crea Tabaski/Créa Tabaski Bus.pdf',
                        'status' => 'prêt',
                    ],
                ],
            ],
            [
                'title' => 'Pack fichiers sources',
                'description' => 'PSD et ressources photo pour décliner la campagne Tabaski sur mesure.',
                'date' => 'sept 2025',
                'status' => 'completed',
                'icon' => 'delivery',
                'anchor' => 'pack-sources-tabaski',
                'assets' => [
                    [
                        'type' => 'source',
                        'label' => 'Créa Tabaski officielle (PSD)',
                        'href' => '/media/Crea Tabaski/Créa Tabaski Officiel.psd',
                        'status' => 'téléchargeable',
                    ],
                    [
                        'type' => 'source',
                        'label' => 'Variantes bus & affichage',
                        'href' => '/media/Crea Tabaski/Créa Tabaski Bus.psd',
                        'status' => 'téléchargeable',
                    ],
                    [
                        'type' => 'source',
                        'label' => 'Variantes créa (pack)',
                        'href' => '/media/Crea Tabaski/Créa Tabaski - Modif M. Lam.psd',
                        'status' => 'téléchargeable',
                    ],
                    [
                        'type' => 'source',
                        'label' => 'Photos & ressources',
                        'href' => '/media/Crea Tabaski/Ressources/elj0801_urban_street_gutter_in_Dakar_during_Tabaski_discarded_6e33d3c4-57d5-4d15-b919-8cd698af7981_0.png',
                        'status' => 'à exploiter',
                    ],
                ],
            ],
        ],
    ],

    'crea-hivernage' => [
        'name' => 'Créa Hivernage',
        'status' => 'TERMINÉ',
        'start' => '01 juin 2025',
        'end' => '31 août 2025',
        'progress' => 100,
        'cover_image' => '/media/Créa Hivernage/Créa Hivernage 2.png',
        'cover_image_mobile' => '/media/Créa Hivernage/Créa Hivernage.png',
        'objective' => 'Proposer une campagne de sensibilisation dédiée à l’hivernage : messages de prévention, visuels pédagogiques et fichiers sources pour déclinaison locale.',
        'contact' => [
            'name' => 'Ousmane Manel FALL',
            'role' => 'Directeur Artistique',
            'phone' => '773478428',
            'email' => 'ousmane.fall@levellagency.com',
            'avatar' => '/media/photo_ousmane.jpg',
            'avatar_position' => 'top',
        ],
        'timeline_intro' => [
            'À partir du plan digital Gamou, nous avons extrait les messages pertinents pour la saison des pluies afin d’en faire une campagne autonome et réactive.',
            'Les visuels ci-dessous sont prêts à être diffusés ou adaptés par les équipes ONAS.',
        ],
        'timeline' => [
            [
                'title' => 'Cadrage éditorial',
                'description' => 'Définition des enjeux, audiences et messages prioritaires pour l’hivernage.',
                'date' => 'juin 2025',
                'status' => 'completed',
                'icon' => 'analysis',
                'anchor' => 'cadrage-editorial-hivernage',
                'narrative_before' => 'Nous avons isolé les situations critiques de la saison des pluies (gestion des déchets, entretien des caniveaux, appels d’urgence) pour préparer une prise de parole utile et pédagogique.',
            ],
            [
                'title' => 'Kit social media',
                'description' => 'Créations pour anticiper, informer et réagir pendant les épisodes de pluie.',
                'date' => 'juil 2025',
                'status' => 'completed',
                'icon' => 'social',
                'anchor' => 'kit-social-hivernage',
                'images' => [
                    '/media/Créa Hivernage/Créa Hivernage.png',
                    '/media/Créa Hivernage/Créa Hivernage 2.png',
                    '/media/Créa Hivernage/Créa Hivernage 3.png',
                ],
                'images_display' => 'modal',
                'images_button_label' => 'Afficher le kit social Hivernage',
            ],
            [
                'title' => 'Fichiers sources',
                'description' => 'PSD maître pour décliner la campagne Hivernage (formats social & print).',
                'date' => 'août 2025',
                'status' => 'completed',
                'icon' => 'goodies',
                'anchor' => 'supports-terrain-hivernage',
                'assets' => [
                    [
                        'type' => 'source',
                        'label' => 'Créa Hivernage (PSD)',
                        'href' => '/media/Créa Hivernage/Créa Hivernage.psd',
                        'status' => 'téléchargeable',
                    ],
                ],
            ],
        ],
    ],

    'strategie' => [
        'name' => 'Stratégie 2025',
        'status' => 'EN COURS',
        'start' => '10 oct 2025',
        'due' => '30 nov 2025',
        'progress' => 68,
        'cover_image' => '/media/onas-strategy.jpg',
        'objective' => 'Définition du positionnement ONAS et élaboration du plan d’action 2025 pour les communautés, basé sur la réalité terrain.',
        'contact' => [
            'name' => 'Elhadji NDIAYE',
            'role' => 'CEO Levell',
            'phone' => '+221 776789212',
            'email' => 'elhadji.ndiaye@levellagency.com',
            'avatar' => '/media/photo_elj.jpg',
            'avatar_position' => 'top',
        ],
        'timeline' => [
            [
                'title' => 'Analyse',
                'description' => 'Lecture du contexte, enjeux critiques terrain, attentes usagers.',
                'date' => 'oct 2025',
                'status' => 'completed',
                'icon' => 'analysis',
            ],
            [
                'title' => 'Positionnement',
                'description' => 'Posture publique de l’ONAS et messages clés institutionnels.',
                'date' => 'nov 2025',
                'status' => 'in-progress',
                'icon' => 'positioning',
            ],
            [
                'title' => 'Plan d’action',
                'description' => 'Feuille de route opérationnelle 2025 : axes, responsabilités, calendrier.',
                'date' => 'déc 2025',
                'status' => 'future',
                'icon' => 'roadmap',
            ],
        ],
    ],

    'formation' => [
        'name' => 'Formation',
        'status' => 'EN COURS',
        'start' => '20 oct 2025',
        'due' => '12 déc 2025',
        'progress' => 45,
        'cover_image' => '/media/onas-training.jpg',
        'objective' => 'Programme d\'acculturation des équipes ONAS : posture publique, communication de crise, outils digitaux et pédagogie terrain.',
        'contact' => [
            'name' => 'Elhadji NDIAYE',
            'role' => 'CEO Levell',
            'phone' => '+221 776789212',
            'email' => 'elhadji.ndiaye@levellagency.com',
            'avatar' => '/media/photo_elj.jpg',
            'avatar_position' => 'top',
        ],
        'timeline' => [
            [
                'title' => 'Formation Réseaux sociaux',
                'description' => 'Bonnes pratiques d\'expression publique institutionnelle.',
                'date' => 'oct 2025',
                'status' => 'completed',
                'icon' => 'social',
            ],
            [
                'title' => 'Formation Communauté',
                'description' => 'Relation directe avec les communautés, pédagogie sur les bons gestes.',
                'date' => 'oct 2025',
                'status' => 'completed',
                'icon' => 'community',
            ],
            [
                'title' => 'Changement de comportement',
                'description' => 'Comment faire évoluer les pratiques des usagers.',
                'date' => 'en cours',
                'status' => 'in-progress',
                'icon' => 'behaviour',
            ],
            [
                'title' => 'Gestion de crise',
                'description' => 'Posture et discours en situation sensible (inondations, débordements).',
                'date' => 'à venir',
                'status' => 'future',
                'icon' => 'crisis',
            ],
            [
                'title' => 'Outils digitaux',
                'description' => 'Prise en main des outils de suivi et reporting terrain.',
                'date' => 'à venir',
                'status' => 'future',
                'icon' => 'digital',
            ],
        ],
    ],

    'site-web' => [
        'name' => 'Site web',
        'status' => 'EN COURS',
        'start' => '15 oct 2025',
        'due' => '15 déc 2025',
        'progress' => 54,
        'cover_image' => '/media/desktop.png',
        'cover_image_mobile' => '/media/desktop_mobile.png',
        'objective' => 'Mise en ligne d’un site ONAS réarchitecturé, aligné sur la nouvelle charte et optimisé pour guider les usagers vers les services prioritaires.',
        'timeline_intro' => [
            'Le projet du nouveau site web de l’ONAS a été lancé dans un contexte où les équipes de l’ONAS étaient fortement mobilisées par la période d’hivernage. Nous avons donc choisi d’adopter une approche proactive : avancer en interne sur toutes les étapes possibles, pour ne pas perdre de temps.',
        ],
        'news' => [
            [
                'title' => 'Version bêta en ligne',
                'date' => '10 nov 2025',
                'description' => 'Parcours complet visible sur la version test avant bascule vers la charte finale.',
                'image' => '/media/Version beta (contenu existant)_mobile.png',
                'anchor' => 'version-beta-contenu-existant',
            ],
            [
                'title' => 'Charte graphique validée avec le comité ONAS',
                'date' => '08 nov 2025',
                'description' => 'Feuille de route UI/UX finalisée pour intégration avant fin du mois.',
                'image' => '/media/onas-branding.jpg',
                'anchor' => 'integration-charte-graphique-validee',
            ],
            [
                'title' => 'Sprint développement V1 lancé',
                'date' => '05 nov 2025',
                'description' => 'Equipe Levell mobilisée sur l’intégration du contenu prioritaire.',
                'image' => '/media/onas-web.png',
                'anchor' => 'developpement-v1',
            ],
            [
                'title' => 'Tests accessibilité programmés',
                'date' => '02 nov 2025',
                'description' => 'Audit préliminaire prévu pour garantir la conformité RGAA.',
                'image' => '/media/hero-sky.jpg',
                'anchor' => 'tests-mise-en-ligne',
            ],
        ],
        'contact' => [
            'name' => 'SIDY BOUYA NDIAYE',
            'role' => 'IT Manager',
            'phone' => '762253530',
            'email' => 'sidy.ndiaye@levellagency.com',
            'avatar' => '/media/nouvelle_photo_sidy.jpeg',
            'avatar_position' => 'top',
        ],
        'timeline' => [
            [
                'title' => 'Audit de l’ancien site web',
                'description' => 'Analyse UX, analytics et accessibilité.',
                'date' => 'oct 2025',
                'status' => 'completed',
                'icon' => 'audit',
                'background_image' => '/media/audit.jpg',
                'background_overlay' => 'linear-gradient(90deg, rgba(9,18,9,0.98) 0%, rgba(9,18,9,0.94) 52%, rgba(9,18,9,0.85) 72%, rgba(9,18,9,0.65) 86%, rgba(9,18,9,0.32) 98%)',
                'anchor' => 'audit-ancien-site-web',
                'assets' => [
                    [
                        'type' => 'pdf',
                        'label' => 'Rapport d’audit',
                        'href' => '/media/Audit_Site_ONAS.pdf',
                        'status' => 'prêt',
                    ],
                    [
                        'type' => 'link',
                        'label' => 'Backlog actions',
                        'status' => 'à intégrer',
                    ],
                ],
                'narrative_before' => 'Nous avons commencé par un audit approfondi de l’ancien site web. Cet audit nous a rapidement montré qu’une refonte complète était nécessaire, tant sur le plan technique que sur la structure du contenu.',
            ],
            [
                'title' => 'Restructuration du contenu',
                'description' => 'Menu et architecture réorganisés.',
                'date' => 'oct 2025',
                'status' => 'completed',
                'icon' => 'structure',
                'background_image' => '/media/Restructuration du contenu.png',
                'background_overlay' => 'linear-gradient(90deg, rgba(9,18,9,0.98) 0%, rgba(9,18,9,0.94) 52%, rgba(9,18,9,0.85) 72%, rgba(9,18,9,0.65) 86%, rgba(9,18,9,0.32) 98%)',
                'anchor' => 'restructuration-du-contenu',
                'pdf' => '/media/Site ONAS Restructuration du contenu.pdf',
                'assets' => [
                    [
                        'type' => 'doc',
                        'label' => 'Plan d’arborescence',
                        'href' => '/media/Site ONAS Restructuration du contenu.pdf',
                        'status' => 'prêt',
                    ],
                ],
                'narrative_before' => 'Nous avons ensuite restructuré le contenu : repensé les menus, simplifié l’arborescence et organisé l’information pour la rendre plus fluide et cohérente.',
            ],
            [
                'title' => 'Adaptation du design temporaire',
                'description' => 'Wireframes + maquettes identité transitoire.',
                'date' => 'oct 2025',
                'status' => 'completed',
                'icon' => 'design',
                'background_image' => '/media/Adaptation du design temporaire.png',
                'background_overlay' => 'linear-gradient(90deg, rgba(9,18,9,0.98) 0%, rgba(9,18,9,0.94) 52%, rgba(9,18,9,0.85) 72%, rgba(9,18,9,0.65) 86%, rgba(9,18,9,0.32) 98%)',
                'anchor' => 'adaptation-du-design-temporaire',
                'assets' => [
                    [
                        'type' => 'figma',
                        'label' => 'Wireframes Figma',
                        'href' => 'https://www.figma.com/design/zHLj28ClfOC1mlDDmgOBbt/kam?node-id=0-1&t=70SxkwjWpnUrGeA9-1',
                        'status' => 'prêt',
                    ],
                ],
                'narrative_before' => 'Sur cette base, nous avons conçu un nouveau design inspiré de la charte graphique en cours d’élaboration. Même si cette charte n’était pas encore validée, nous avons produit un wireframe et une maquette temporaire pour matérialiser la future expérience utilisateur.',
            ],
            [
                'title' => 'Version beta (contenu existant)',
                'description' => 'Déploiement d’une version bêta WordPress pour tester l’architecture.',
                'date' => 'oct 2025',
                'status' => 'completed',
                'icon' => 'beta',
                'background_image' => '/media/Version beta (contenu existant).png',
                'background_image_mobile' => '/media/Version beta (contenu existant)_mobile.png',
                'background_overlay' => 'linear-gradient(90deg, rgba(9,18,9,0.98) 0%, rgba(9,18,9,0.94) 52%, rgba(9,18,9,0.85) 72%, rgba(9,18,9,0.65) 86%, rgba(9,18,9,0.32) 98%)',
                'anchor' => 'version-beta-contenu-existant',
                'assets' => [
                    [
                        'type' => 'link',
                        'label' => 'Version bêta WordPress',
                        'href' => 'https://www.levellagency.com/onas/',
                        'status' => 'prêt',
                    ],
                ],
                'narrative_before' => 'Dans la continuité, nous avons développé une version bêta du site, en nous appuyant sur le contenu existant de l’ancien site, afin d’avoir une base technique déjà opérationnelle.',
            ],
            [
                'title' => 'Architecture finale ONAS',
                'description' => 'Co-design de la navigation définitive.',
                'date' => '12 nov 2025',
                'status' => 'future',
                'icon' => 'architecture',
                'anchor' => 'architecture-finale-onas',
                'assets' => [
                    ['type' => 'doc', 'label' => 'Atelier ONAS x Levell', 'status' => 'en cours'],
                ],
                'narrative_before' => 'Aujourd’hui, nous arrivons à une étape clé : celle de la définition de l’architecture finale avec l’équipe de l’ONAS.',
            ],
            [
                'title' => 'Intégration charte graphique validée',
                'description' => 'Déclinaison maquette graphique officielle.',
                'date' => 'fin nov 2025',
                'status' => 'on-hold',
                'icon' => 'charter',
                'anchor' => 'integration-charte-graphique-validee',
                'assets' => [
                    ['type' => 'figma', 'label' => 'Maquette finale', 'status' => 'à intégrer'],
                ],
            ],
            [
                'title' => 'Développement V1',
                'description' => 'Intégration graphique complète + nouvelles sections.',
                'date' => 'déc 2025',
                'status' => 'future',
                'icon' => 'dev',
                'anchor' => 'developpement-v1',
                'assets' => [
                    ['type' => 'source', 'label' => 'Repo V1', 'status' => 'à intégrer'],
                ],
            ],
            [
                'title' => 'Optimisation & SEO',
                'description' => 'Performances, structure SEO et redirections.',
                'date' => 'déc 2025',
                'status' => 'future',
                'icon' => 'seo',
                'background_image' => '/media/Optimisation & SEO.jpg',
                'background_overlay' => 'linear-gradient(90deg, rgba(9,18,9,0.98) 0%, rgba(9,18,9,0.94) 52%, rgba(9,18,9,0.85) 72%, rgba(9,18,9,0.65) 86%, rgba(9,18,9,0.32) 98%)',
                'anchor' => 'optimisation-seo',
                'assets' => [
                    ['type' => 'pdf', 'label' => 'Checklist SEO', 'status' => 'à intégrer'],
                ],
            ],
            [
                'title' => 'Tests & mise en ligne',
                'description' => 'Recette finale, monitoring et communication.',
                'date' => '15 déc 2025',
                'status' => 'future',
                'icon' => 'launch',
                'background_image' => '/media/Tests & mise en ligne.jpg',
                'background_overlay' => 'linear-gradient(90deg, rgba(9,18,9,0.98) 0%, rgba(9,18,9,0.94) 52%, rgba(9,18,9,0.85) 72%, rgba(9,18,9,0.65) 86%, rgba(9,18,9,0.32) 98%)',
                'anchor' => 'tests-mise-en-ligne',
                'assets' => [
                    ['type' => 'link', 'label' => 'Plan de go-live', 'status' => 'à intégrer'],
                ],
            ],
        ],
    ],

    'charte-graphique' => [
        'name' => 'Charte graphique',
        'status' => 'EN COURS',
        'start' => '08 oct 2025',
        'due' => '05 nov 2025',
        'progress' => 72,
        'cover_image' => '/media/onas-branding.jpg',
        'objective' => 'Modernisation de l\'identité ONAS : cohérence visuelle, reconnaissance institutionnelle, supports homogènes print & digital.',
        'contact' => [
            'name' => 'Ousmane Manel FALL',
            'role' => 'Directeur Artistique',
            'phone' => '773478428',
            'email' => 'ousmane.fall@levellagency.com',
            'avatar' => '/media/photo_ousmane.jpg',
            'avatar_position' => 'top',
        ],
        'timeline' => [
            [
                'title' => 'Variantes logos',
                'description' => 'Exploration autour du logotype ONAS : lisibilité, usage digital, déclinaisons.',
                'date' => 'oct 2025',
                'status' => 'completed',
                'icon' => 'logos',
            ],
            [
                'title' => 'Univers Graphique',
                'description' => 'Palette couleurs, typographies, iconographie, grammaire visuelle.',
                'date' => 'oct 2025',
                'status' => 'completed',
                'icon' => 'universe',
            ],
            [
                'title' => 'Papeterie',
                'description' => 'En-têtes officiels, cartes, documents internes normalisés.',
                'date' => 'en cours',
                'status' => 'in-progress',
                'icon' => 'papeterie',
            ],
            [
                'title' => 'Branding',
                'description' => 'Définition du langage visuel public ONAS (ton, posture, image).',
                'date' => 'à venir',
                'status' => 'future',
                'icon' => 'branding',
            ],
            [
                'title' => 'Goodies',
                'description' => 'Objets et supports physiques cohérents avec la nouvelle identité.',
                'date' => 'à venir',
                'status' => 'future',
                'icon' => 'goodies',
            ],
        ],
    ],
];
