<?php

return [
    'nav' => [
        [
            'label' => 'Accueil',
            'slug' => null,
            'target' => 'onas.dashboard',
            'children' => [],
        ],
        [
            'label' => 'Stratégie',
            'slug' => 'strategie',
            'target' => 'onas.projects.show',
            'children' => ['strategie', 'plan-digital-gamou', 'formation'],
        ],
        [
            'label' => 'Créas',
            'slug' => 'charte-graphique',
            'target' => 'onas.projects.show',
            'children' => ['charte-graphique', 'creas-gamou', 'creas-tabaski', 'crea-hivernage'],
        ],
        [
            'label' => 'Vidéo',
            'slug' => 'spot-sama-naweet',
            'target' => 'onas.projects.show',
            'children' => ['spot-sama-naweet', 'gamou'],
        ],
        [
            'label' => 'Dev',
            'slug' => 'site-web',
            'target' => 'onas.projects.show',
            'children' => [],
        ],
    ],
    'projects' => [
        [
            'name' => 'Plan digital Gamou',
            'slug' => 'plan-digital-gamou',
            'status' => 'TERMINÉ',
            'progress' => 100,
            'start' => '01 sept 2025',
            'end' => '30 nov 2025',
            'thumbnail' => '/media/Gamou/Onas-Meteo Template.webp',
        ],
        [
            'name' => 'Créas Gamou',
            'slug' => 'creas-gamou',
            'status' => 'TERMINÉ',
            'progress' => 100,
            'start' => '15 oct 2025',
            'end' => '30 nov 2025',
            'thumbnail' => '/media/Gamou/Onas-Gamou.webp',
        ],
        [
            'name' => 'Campagne Gamou',
            'slug' => 'gamou',
            'status' => 'TERMINÉ',
            'progress' => 100,
            'start' => '05 sept 2025',
            'end' => '18 oct 2025',
            'thumbnail' => '/media/onas-gamou.jpg',
        ],
        [
            'name' => 'Spot Sama Naweet',
            'slug' => 'spot-sama-naweet',
            'status' => 'TERMINÉ',
            'progress' => 100,
            'start' => '01 sept 2025',
            'end' => '12 oct 2025',
            'thumbnail' => '/media/onas-spot.jpg',
        ],
        [
            'name' => 'Créas Tabaski',
            'slug' => 'creas-tabaski',
            'status' => 'TERMINÉ',
            'progress' => 100,
            'start' => '01 août 2025',
            'end' => '30 sept 2025',
            'thumbnail' => '/media/Crea Tabaski/Créa Tabaski Officiel Mockup 2.png',
        ],
        [
            'name' => 'Créa Hivernage',
            'slug' => 'crea-hivernage',
            'status' => 'TERMINÉ',
            'progress' => 100,
            'start' => '01 juin 2025',
            'end' => '31 août 2025',
            'thumbnail' => '/media/Créa Hivernage/Créa Hivernage 2.png',
        ],
        [
            'name' => 'Stratégie 2025',
            'slug' => 'strategie',
            'status' => 'EN COURS',
            'progress' => 68,
            'start' => '10 oct 2025',
            'due' => '30 nov 2025',
            'thumbnail' => '/media/onas-strategy.jpg',
        ],
        [
            'name' => 'Site web',
            'slug' => 'site-web',
            'status' => 'EN COURS',
            'progress' => 54,
            'start' => '15 oct 2025',
            'due' => '15 déc 2025',
            'thumbnail' => '/media/onas-web.png',
        ],
        [
            'name' => 'Formation',
            'slug' => 'formation',
            'status' => 'EN COURS',
            'progress' => 45,
            'start' => '20 oct 2025',
            'due' => '12 déc 2025',
            'thumbnail' => '/media/onas-training.jpg',
        ],
        [
            'name' => 'Charte graphique',
            'slug' => 'charte-graphique',
            'status' => 'EN COURS',
            'progress' => 72,
            'start' => '08 oct 2025',
            'due' => '05 nov 2025',
            'thumbnail' => '/media/onas-branding.jpg',
        ],
    ],
    'hero_tiles' => [
        [
            'id' => 'p-spot-sama',
            'title' => 'Spot Sama Naweet',
            'slug' => 'spot-sama-naweet',
            'status' => 'termine',
            'summary' => 'Spot pédagogique Sama Naweet pour promouvoir les bons gestes d’assainissement.',
            'image' => '/media/onas-spot.jpg',
            'icon' => 'sparkles',
        ],
        [
            'id' => 'p-campagne-gamou',
            'title' => 'Campagne Gamou',
            'slug' => 'gamou',
            'status' => 'termine',
            'summary' => 'Captation vidéo et montage final pour valoriser l’action terrain de l’ONAS.',
            'image' => '/media/onas-gamou.jpg',
            'icon' => 'circle-play',
        ],
        [
            'id' => 'p-strategie',
            'title' => 'Stratégie ONAS',
            'slug' => 'strategie',
            'status' => 'encours',
            'summary' => 'Plan d’action 2025 pour les communautés : positionnement, messages et feuille de route.',
            'image' => '/media/onas-strategy.jpg',
            'icon' => 'navigation',
        ],
        [
            'id' => 'p-site-web',
            'title' => 'Site web',
            'slug' => 'site-web',
            'status' => 'encours',
            'summary' => 'Refonte du portail public avec un parcours usager simplifié.',
            'image' => '/media/onas-web.png',
            'icon' => 'earth',
        ],
        [
            'id' => 'p-formation',
            'title' => 'Formation',
            'slug' => 'formation',
            'status' => 'encours',
            'summary' => 'Série de workshops ONAS pour acculturer les équipes aux outils et postures.',
            'image' => '/media/onas-training.jpg',
            'icon' => 'users-round',
        ],
        [
            'id' => 'p-charte',
            'title' => 'Charte graphique',
            'slug' => 'charte-graphique',
            'status' => 'encours',
            'summary' => 'Modernisation de l’identité ONAS pour homogénéiser tous les supports.',
            'image' => '/media/onas-branding.jpg',
            'icon' => 'shield-check',
        ],
    ],
    'gamou_focus' => [
        [
            'id' => 'focus-plan',
            'title' => 'Plan digital Gamou',
            'slug' => 'plan-digital-gamou',
            'status' => 'termine',
            'summary' => 'Document stratégique validé – objectifs, messages et rétroplanning de production.',
            'icon' => 'navigation',
        ],
        [
            'id' => 'focus-creas',
            'title' => 'Créas Gamou',
            'slug' => 'creas-gamou',
            'status' => 'termine',
            'summary' => 'Kit visuel complet livré (social, print) + PSD sources pour adaptation locale.',
            'icon' => 'sparkles',
        ],
        [
            'id' => 'focus-video',
            'title' => 'Vidéo Gamou',
            'slug' => 'gamou',
            'status' => 'termine',
            'summary' => 'Visionner la vidéo finale de la campagne Gamou (montage livré).',
            'hash' => 'video',
            'icon' => 'circle-play',
        ],
    ],
    'crea_highlights' => [
        [
            'id' => 'highlight-tabaski',
            'title' => 'Créas Tabaski',
            'slug' => 'creas-tabaski',
            'status' => 'termine',
            'summary' => 'Maquette officielle, déclinaisons bus et pack PSD prêts à l’emploi.',
            'icon' => 'sparkles',
        ],
        [
            'id' => 'highlight-hivernage',
            'title' => 'Créa Hivernage',
            'slug' => 'crea-hivernage',
            'status' => 'termine',
            'summary' => 'Campagne prévention hivernage : visuels pédagogiques et PSD maître.',
            'icon' => 'sparkles',
        ],
    ],
    'project_icons' => [
        'Plan digital Gamou' => 'navigation',
        'Créas Gamou' => 'sparkles',
        'Campagne Gamou' => 'circle-play',
        'Spot Sama Naweet' => 'sparkles',
        'Créas Tabaski' => 'sparkles',
        'Créa Hivernage' => 'sparkles',
        'Stratégie 2025' => 'navigation',
        'Site web' => 'earth',
        'Formation' => 'users-round',
        'Charte graphique' => 'shield-check',
    ],
];
